### ISSUE TITLE
[US7][MAP] L'utente visitatore vede i popoli autori dei manufatti su una mappa

### ISSUE THREAD

**Issue by feroda** [befair/soulShape#10]

**Comment by Azzeccagarbugli** [comment]
Sulla homepage di soulShape l'utente visitatore potrà vedere una mappa sulla quale sono presenti dei Marker che segnalano la posizione del popolo indigeno e al click delle informazioni relative alla popolazione stessa.

In allegato l'immagine della mappa:
![immagine2](https://cloud.githubusercontent.com/assets/16477661/17831259/4096fdd4-66e4-11e6-9aae-379d67abd05e.png)
