### ISSUE TITLE
[US8][SOCIAL] L'utente registrato commenta/vota un manufatto

### ISSUE THREAD

**Issue by feroda** [befair/soulShape#11]

**Comment by Azzeccagarbugli** [comment]
L'utente, anche se non loggato, può accedere alla sezione del 3D Market visualizzandone i contenuti. In questo caso però non potrà lasciare commenti o dare una preferenza al manufatto, potrà però aggiungere quest'ultimo al carrello e continuare all'acquisto di esso solamente dopo aver completato la registrazione a soulShape.

In allegato l'immagine rappresentate la sezione commenti e valutazioni:
![immagine1](https://cloud.githubusercontent.com/assets/16477661/17831226/3d022a96-66e3-11e6-8486-9f397e5ab6b1.png)
