### ISSUE TITLE
[POPOLI] una pagina per ogni popolo

### ISSUE THREAD

**Issue by feroda** [befair/soulShape#13]
Per ogni popolo si crea una pagina Wordpress descrittiva, compilata da Pierpaolo. Il link verrà associato ad un gruppo. Vedi issue #12

**Comment by Azzeccagarbugli** [comment]
Nella categoria "Indigenous People" è possibile visualizzare i vari popoli indegeni. Per il momento sono presente i popoli: Maya, Inca e Murri. Ad ognuno di essi corrisponde una pagina contente una descrizione e a fondo di quest'ultima due pulsanti. Il primo rimanda l'utente al 3D Market, filtrato con i prodotti della medesima popolazione mentre il secondo, attualmente, manda alla descrizione del popolo su Wikipedia.

In allegato l'immagine rappresentate la pagina:
![immagine](https://cloud.githubusercontent.com/assets/16477661/17831147/a44a6012-66e1-11e6-9908-a64f2d9f167b.png)
