### ISSUE TITLE
[BUG] Url di registrazione Wordpress "Not Found"

### ISSUE THREAD

**Issue by feroda** [befair/soulShape#14]
Se un utente non registrato va su "Upload" riceve la richiesta di login con il link `http://.../wp-login.php?action=register` che restituisce un 404.

Potrebbe essere risolto a livello di redirezione con server web redirezionando l'url sulla pagina corretta `http://.../soulShape/wp/soulshape.earth/?page_id=113`

**Comment by Radeox** [comment]
Fixato :)
