### ISSUE TITLE
[REGISTRATION] si può registrare anche un utente "senza popolo"

### ISSUE THREAD

**Issue by feroda** [befair/soulShape#15]
Nella pagina di registrazione la scelta del popolo deve essere opzionale. Di base deve essere scelta l'opzione "Nessuno", l'opzione dovrebbe essere chiamata "Popolo indigeno"

**Comment by Radeox** [comment]
Reso opzionale e con "Nessuno" di default
![screenshot_20160830_102144](https://cloud.githubusercontent.com/assets/9751015/18081668/955b557c-6e9b-11e6-8fbc-9ecb80fe2939.png)
