### ISSUE TITLE
[SHOP] Informazioni sul popolo ed era in primo piano

### ISSUE THREAD

**Issue by feroda** [befair/soulShape#17]
No sottotab nello shop, le informazioni sul popolo e l'era di creazione vanno a fianco del player 3d

**Comment by Radeox** [comment]
![spectacle m16660](https://cloud.githubusercontent.com/assets/9751015/17937940/320902e2-6a24-11e6-9bbf-0159e4b88c70.png)

**Comment by feroda** [comment]
@Radeox great @Radeox, would you please put also the short description over population and age?👍

**Comment by Radeox** [comment]
Like this @feroda?
![spectacle j17252](https://cloud.githubusercontent.com/assets/9751015/17938621/fc9534ac-6a26-11e6-8131-1a4a991a3098.png)

**Comment by feroda** [comment]
@Radeox You are the man! 👍😜
