### ISSUE TITLE
[US0] L'utente indigeno definisce il suo popolo

### ISSUE THREAD

**Issue by feroda** [befair/soulShape#5]

**Comment by Azzeccagarbugli** [comment]
L'utente indigeno durante la fase di registrazione potrà selezionare il suo popolo da una lista di predefiniti.

L'immagine contente la sezione di scelta:
![immagine5](https://cloud.githubusercontent.com/assets/16477661/17831407/fada88ac-66e7-11e6-82c0-7a523268ca28.png)
