### ISSUE TITLE
[US3] L'utente indigeno associa un testo descrittivo (storia/descrizione/ricetta) al modello caricato

### ISSUE THREAD

**Issue by feroda** [befair/soulShape#7]
La gestione di queste informazioni dovrebbe essere possibile sia da app (probabilmente in futuro) sia da web.

**Comment by Azzeccagarbugli** [comment]
L'utente indigeno grazie ad una sezione creata appositamente chiamata "Upload" potrà inserire il suo manufatto acquisito precedentemente e collegare a quest'ultimo una descrizione breve e una più approfondita, un'epoca e una popolazione, delle misure e infine, ovviamente, il file 3D del manufatto e un'immagine di anteprima.
Va sottolineato il merito di @Radeox in quanto è riuscito a sfruttare a pieno le potenzialità delle API offerte da Skecthfab e a ottenere un risultato ottimo per la visualizzazione e per la parte descrittiva del modello caricato.

In allegato l'immagine dell'upload del prodotto:
![immagine4](https://cloud.githubusercontent.com/assets/16477661/17831380/5fa6355c-66e7-11e6-9c40-e0bb1fd86186.png)
