### ISSUE TITLE
[US5][SEARCH] L'utente anonimo visita prodotti e popoli per origine geografica, etnica, epoca, tipo di manufatto

### ISSUE THREAD

**Issue by feroda** [befair/soulShape#8]

**Comment by Azzeccagarbugli** [comment]
L'utente nella sezione del Market potrà filtrare i prodotti secondo ordine geografico, etnico, epoca e tipo di manufatto. 

In allegato l'immagine del filtro presente nello shop:
![immagine3](https://cloud.githubusercontent.com/assets/16477661/17831336/1f8d23e6-66e6-11e6-9cc3-aab4062aa834.png)
