### ISSUE TITLE
[US6] L'utente registrato acquista un prodotto caricato su Sketchfab.com

### ISSUE THREAD

**Issue by feroda** [befair/soulShape#9]

**Comment by Azzeccagarbugli** [comment]
Durante la schermata di acquisto del prodotto l'utente può scegliere se registrarsi al sito soulShape o comparare l'articolo compilando solamente una from generica con dati rilevanti la fatturazione.

**Comment by Azzeccagarbugli** [comment]
L'utente solamente se registrato potrà acquistare un prodotto, sia ricetta che manufatto, e visualizzarne una breve descrizione, una lunga descrizione e delle opinioni di altri acquirenti. L'acquisto avvera grazie all'ausilio del plug-in WooCommerce. Quest'ultimo guiderà l'utente passo-passo nella procedura del acquisto, ovvero, l'utente dovrà compilare dei moduli pre-compilati contenti dati sensibili, quali l'indirizzo e i dati di pagamento, e in questo modo si concluderà l'acquisto.

L'immagine dell'acquisto del prodotto:
![immagine2](https://cloud.githubusercontent.com/assets/16477661/17831309/3d54d69a-66e5-11e6-9c3c-bffd8b1ffc64.png)
